apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "Kubernetes"
  kustomize.toolkit.fluxcd.io/substitute: disabled

# Generate a ConfigMap for each dashboard
configMapGenerator:
  #################################################
  # Views Dashboards
  #################################################

  - name: dashboards-k8s-views-global
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-views-global.json

  - name: dashboards-k8s-views-namespaces
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-views-namespaces.json

  - name: dashboards-k8s-views-nodes
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-views-nodes.json

  - name: dashboards-k8s-views-pods
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-views-pods.json

  #################################################
  # System / Addons Dashboards
  #################################################

  - name: dashboards-k8s-system-api-server
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-system-api-server.json

  - name: dashboards-k8s-system-coredns
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-system-coredns.json

  - name: dashboards-k8s-addons-prometheus
    files:
      - https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/refs/heads/master/dashboards/k8s-addons-prometheus.json
