apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "MongoDB"
  kustomize.toolkit.fluxcd.io/substitute: disabled

configMapGenerator:
  - name: dashboard-mongodb-opstree
    files:
      - mongodb-opstree.json=https://grafana.com/api/dashboards/16490/revisions/1/download
