apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Global options
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "MongoDB"
  kustomize.toolkit.fluxcd.io/substitute: disabled

configMapGenerator:
  - name: dashboard-mongodb
    files:
      # https://grafana.com/grafana/dashboards/20867-mongodb-dashboard/
      - mongodb.json=https://grafana.com/api/dashboards/20867/revisions/1/download
