apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Global options
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: dashboard-flux
    files:
      - https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/control-plane.json
      - https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/cluster.json
      - https://raw.githubusercontent.com/fluxcd/flux2-monitoring-example/refs/heads/main/monitoring/configs/dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
      annotations:
        grafana_folder: "Flux"
        kustomize.toolkit.fluxcd.io/substitute: disabled
